# Generated by Django 5.2.3 on 2025-06-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organixer',
            new_name='organizer',
        ),
    ]
