services:
  - type: web
    name: event-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn event_menagement_project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true